name: renovate

on:
  schedule:
    - cron: '0 3 * * 1' # run weekly on Mondays at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.19
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_AUTODISCOVER: "false"
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
